### ISSUE TITLE
Syntax error when transpiling babel code

### ISSUE THREAD

**Issue by as-cii** [simonmeusel/atom-setup-manager-package#1]
In the process of upgrading babel in Atom core (https://github.com/atom/atom/pull/13823) we have noticed this package doesn't transpile correctly. In particular, we have found the following errors:

* `atom-setup-manager-package/lib/checkout.js: 'super' outside of function or class (17:6)`

To ensure your package keeps working after we will merge and release the aforementioned pull request, please make sure to fix these errors and publish a new version.

Please, let me know if you have any questions or concerns and if I can help somehow. Thanks!

**Comment by simonmeusel** [comment]
Dosen't make sense to me?! Its inside a function (Constructor of `CheckoutSetup`, which is subclass of `SelectListView`) and thus inside a class too. I have to say that I'm not very up to data with new javascript syntax ):

**Comment by as-cii** [comment]
I believe the issue is caused by https://github.com/simonmeusel/atom-setup-manager-package/blob/master/lib/checkout.js#L17, which attempts to access `super` inside a closure. Maybe an easy fix could be to use an [arrow function](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions) instead?

**Comment by simonmeusel** [comment]
Yes, you are right! I've now fixed this issue and made some other minor changes.

Fixed with c918ca38882c0abd3ae1322824ad9f93d026651f
