### ISSUE TITLE
Atom Crashing

### ISSUE THREAD

**Issue by Amirkermanshahani** [simonmeusel/atom-setup-manager-package#2]
Hi, Wanted to say as soon as I installed This package , It just crashed all my Atom and made it refresh again and again with a warning i couldn't  read due to the crashing.
It didn't stop so I had to remove the package from .atom packages on my windows.

**Comment by simonmeusel** [comment]
Thank you for your report. Sadly, I'm no longer using Atom and thus this package is unmaintained. Since the internals of Atom likely changed over the last 3 years,  this package no longer works. I'm going to mark it as deprecated.
